import { MenuItem, SignatureDrink, CoffeeJourneyStage, OriginRegion, Testimonial } from "@/types/coffee";

export const siteConfig = {
  name: "AROMA",
  tagline: "CRAFTED FOR YOUR MOMENT.",
  subtext: "Premium coffee, carefully roasted and beautifully crafted for every moment.",
  establishment: "EST. 2024 • SPECIALTY COFFEE",
  address: "Jl. Example No. 21, Tuban, Jawa Timur",
  hours: "OPEN DAILY • 07:00 — 22:00",
  phone: "+62 812-3456-7890",
  email: "hello@aromacoffee.id",
  instagram: "@aromacoffee.id",
  tiktok: "@aromacoffee.official",
  whatsapp: "+6281234567890",
  mapsUrl: "https://maps.google.com/?q=Tuban+Jawa+Timur",
};

export const signatureDrinks: SignatureDrink[] = [
  {
    id: "sig-espresso",
    number: "01",
    name: "SIGNATURE ESPRESSO",
    category: "DOUBLE SHOT • SINGLE ORIGIN",
    description: "Rich full-bodied espresso with velvety crema, delicate dark chocolate depth, roasted hazelnut notes, and lingering golden sweetness.",
    notes: ["Dark Chocolate", "Roasted Hazelnut", "Golden Crema"],
    price: 25000,
    priceFormatted: "Rp 25.000",
    image: "/images/espresso.jpg",
    origin: "Cerrado Mineiro, Brazil",
    roast: "Medium Dark",
  },
  {
    id: "caramel-latte",
    number: "02",
    name: "CARAMEL LATTE",
    category: "ARTISANAL SPECIALTY MILK",
    description: "Silky double ristretto layered over velvety steamed microfoam milk and finished with small-batch artisan salted caramel ribbons.",
    notes: ["Salted Caramel", "Silky Milk", "Toasted Pecan"],
    price: 32000,
    priceFormatted: "Rp 32.000",
    image: "/images/caramel-latte.jpg",
    origin: "Huila, Colombia",
    roast: "Medium Roast",
  },
  {
    id: "cold-brew",
    number: "03",
    name: "COLD BREW RESERVE",
    category: "20-HOUR SLOW EXTRACTION",
    description: "Meticulously steeped for 20 hours in pure glacier-cold water. Incredibly smooth, naturally sweet with citrus bloom and dark honey finish.",
    notes: ["Floral Citrus", "Dark Honey", "Smooth Cocoa"],
    price: 30000,
    priceFormatted: "Rp 30.000",
    image: "/images/cold-brew.jpg",
    origin: "Yirgacheffe, Ethiopia",
    roast: "Light-Medium Roast",
  },
];

export const journeyStages: CoffeeJourneyStage[] = [
  {
    step: 1,
    badge: "STAGE 01",
    title: "THE COFFEE CHERRY",
    subtitle: "High-Altitude Botanical Ripening",
    description: "Hand-picked only at peak brix sugar density between 1,800 to 2,200 meters above sea level on misty mountain slopes.",
    image: "/images/coffee-cherries.jpg",
    origin: "Brazil • Ethiopia",
    roast: "Pre-Harvest",
    notes: "Sweet Red Berries & Honey",
    process: "Selective Handpicked",
  },
  {
    step: 2,
    badge: "STAGE 02",
    title: "PURITY & SEPARATION",
    subtitle: "Natural Fermentation & Washing",
    description: "Fresh cherries undergo slow controlled temperature pulping to preserve natural fruit sugars and develop signature clarity.",
    image: "/images/coffee-cherries.jpg",
    origin: "Guji Highlands",
    roast: "Green Bean",
    notes: "Clean Jasmine • Citrus Peel",
    process: "Washed & Extended Natural",
  },
  {
    step: 3,
    badge: "STAGE 03",
    title: "ARTISANAL ROAST PROFILE",
    subtitle: "Precise Convective Thermodynamics",
    description: "Small batch drum roasting with custom thermal curves, developing internal aromatic oils to achieve deep caramelization without bitterness.",
    image: "/images/beans-pile.jpg",
    origin: "Selected Batches",
    roast: "Custom Micro-Roast",
    notes: "Chocolate • Caramel • Nutty",
    process: "Fluid Bed Convective",
  },
  {
    step: 4,
    badge: "STAGE 04",
    title: "PRECISION MICRON GRIND",
    subtitle: "Uniform Particle Distribution",
    description: "Titanium burr geometry calibrated to exact sub-millimeter tolerances prevents channeling and unlocks multidimensional flavor notes.",
    image: "/images/single-bean.jpg",
    origin: "Single Lot",
    roast: "Medium Roast",
    notes: "Aromatic Volatiles",
    process: "Burr Calibrated 280µm",
  },
  {
    step: 5,
    badge: "STAGE 05",
    title: "GOLDEN NAKED EXTRACTION",
    subtitle: "9-Bar Saturated Hydraulic Pressure",
    description: "Pre-infusion blooming followed by exact 93.5°C water extraction pulls pure concentrated nectar with dense tiger-stripe crema.",
    image: "/images/coffee-extraction.jpg",
    origin: "House Blend",
    roast: "Medium Roast",
    notes: "Dense Crema • Syrupy Body",
    process: "9-Bar Naked Portafilter",
  },
  {
    step: 6,
    badge: "STAGE 06",
    title: "THE MASTERPIECE CUP",
    subtitle: "Crafted For Your Sacred Moment",
    description: "The culmination of craftsmanship, temperature-stabilized luxury ceramic cup with silky microfoam latte art ready for your first sip.",
    image: "/images/hero-cup.jpg",
    origin: "AROMA Reserve",
    roast: "Signature Profile",
    notes: "Balanced • Silky • Unforgettable",
    process: "Artisan Barista Pour",
  },
];

export const origins: OriginRegion[] = [
  {
    id: "brazil",
    country: "BRAZIL",
    region: "Cerrado Mineiro",
    altitude: "1,150 — 1,350 MASL",
    notes: "Chocolate • Nutty • Smooth",
    flavorProfile: ["Dark Chocolate", "Roasted Hazelnut", "Brown Sugar", "Velvety Crema"],
    process: "Natural Sun-Dried",
    description: "Grown in nutrient-rich volcanic soil, our Brazilian microlot delivers a comforting, luxurious base with heavy body and sweet praline finish.",
    color: "#B87945",
    image: "/images/coffee-plantation.jpg",
  },
  {
    id: "ethiopia",
    country: "ETHIOPIA",
    region: "Yirgacheffe & Guji",
    altitude: "1,950 — 2,200 MASL",
    notes: "Floral • Citrus • Bright",
    flavorProfile: ["Jasmine Blossoms", "Bergamot Citrus", "Wild Peach", "Black Tea Finish"],
    process: "Washed & Slow African Bed Dried",
    description: "The spiritual birthplace of Arabica. Grown in natural shade forests at extreme altitudes, presenting ethereal jasmine aromas and sparkling citrus acidity.",
    color: "#C9A66B",
    image: "/images/coffee-cherries.jpg",
  },
  {
    id: "colombia",
    country: "COLOMBIA",
    region: "Huila & Nariño",
    altitude: "1,700 — 2,050 MASL",
    notes: "Caramel • Berry • Balanced",
    flavorProfile: ["Dulce de Leche", "Red Currant", "Sweet Almond", "Juicy Acidity"],
    process: "Extended Anaerobic Washed",
    description: "Surrounded by volcanic ridges and pristine rivers, Huila beans yield the quintessential specialty cup: crystalline balance, vibrant berry sweetness, and velvety caramel.",
    color: "#8C6350",
    image: "/images/coffee-bag.jpg",
  },
];

export const fullMenu: MenuItem[] = [
  // ESPRESSO
  {
    id: "m-esp",
    name: "SIGNATURE ESPRESSO",
    category: "ESPRESSO",
    description: "Rich double ristretto with dark chocolate notes and dense golden crema",
    price: 25000,
    priceFormatted: "Rp 25.000",
    image: "/images/espresso.jpg",
    tags: ["Signature", "Single Origin"],
    notes: "Chocolate • Hazelnut",
    featured: true,
  },
  {
    id: "m-americano",
    name: "AROMA LONG BLACK",
    category: "ESPRESSO",
    description: "Double extraction pulled directly over purified hot water preserving delicate crema",
    price: 26000,
    priceFormatted: "Rp 26.000",
    image: "/images/espresso.jpg",
    tags: ["Bold", "Clean"],
    notes: "Caramel • Roasted Pecan",
  },
  {
    id: "m-cortado",
    name: "SPANISH CORTADO",
    category: "ESPRESSO",
    description: "Equal parts intense espresso and warm silky milk in a 4oz heavy crystal glass",
    price: 28000,
    priceFormatted: "Rp 28.000",
    image: "/images/espresso.jpg",
    tags: ["Balanced", "Rich"],
    notes: "Cocoa • Creamy",
  },

  // MILK
  {
    id: "m-caramel-latte",
    name: "CARAMEL LATTE",
    category: "MILK",
    description: "Silky espresso, steamed milk, and house-made caramelized brown sugar butter drizzle",
    price: 32000,
    priceFormatted: "Rp 32.000",
    image: "/images/caramel-latte.jpg",
    tags: ["Best Seller", "Sweet"],
    notes: "Salted Caramel • Toasted Vanilla",
    featured: true,
  },
  {
    id: "m-velvet-latte",
    name: "VELVET CAFE LATTE",
    category: "MILK",
    description: "Smooth double shot paired with perfectly textured microfoam and custom latte art",
    price: 29000,
    priceFormatted: "Rp 29.000",
    image: "/images/hero-cup.jpg",
    tags: ["Classic", "Silky"],
    notes: "Sweet Milk • Cocoa Powder",
  },
  {
    id: "m-cappuccino",
    name: "CAPPUCCINO ARTISAN",
    category: "MILK",
    description: "Dense, cloud-like foam crown over rich espresso, dusted with organic Indonesian cacao",
    price: 28000,
    priceFormatted: "Rp 28.000",
    image: "/images/hero-cup.jpg",
    tags: ["Frothy", "Comforting"],
    notes: "Chocolate Dust • Cream",
  },
  {
    id: "m-flat-white",
    name: "FLAT WHITE RESERVE",
    category: "MILK",
    description: "Australian-style thin velvety micro-layer allowing pure espresso brightness to sing",
    price: 30000,
    priceFormatted: "Rp 30.000",
    image: "/images/espresso.jpg",
    tags: ["Strong", "Velvety"],
    notes: "Brown Sugar • Toffee",
  },

  // COLD
  {
    id: "m-coldbrew",
    name: "COLD BREW RESERVE",
    category: "COLD",
    description: "Slow-steeped 20-hour cold extraction over handcrafted crystal ice sphere",
    price: 30000,
    priceFormatted: "Rp 30.000",
    image: "/images/cold-brew.jpg",
    tags: ["Slow Steep", "Refreshing"],
    notes: "Bergamot • Dark Honey",
    featured: true,
  },
  {
    id: "m-iced-caramel",
    name: "ICED CARAMEL MACCHIATO",
    category: "COLD",
    description: "Chilled fresh milk, vanilla bean extract, layered espresso and slow caramel drizzle",
    price: 34000,
    priceFormatted: "Rp 34.000",
    image: "/images/caramel-latte.jpg",
    tags: ["Layered", "Iced"],
    notes: "Vanilla Bean • Caramel",
  },
  {
    id: "m-splash-tonic",
    name: "ESPRESSO TONIC BLOOM",
    category: "COLD",
    description: "Single origin espresso floated over botanical tonic water with charred orange wheel",
    price: 33000,
    priceFormatted: "Rp 33.000",
    image: "/images/cold-brew.jpg",
    tags: ["Fizzy", "Citrus"],
    notes: "Citrus Zest • Quinine",
  },

  // NON-COFFEE
  {
    id: "m-matcha",
    name: "UJI CEREMONIAL MATCHA",
    category: "NON-COFFEE",
    description: "Single-origin Kyoto matcha hand-whisked with bamboo chasen and creamy oat milk",
    price: 33000,
    priceFormatted: "Rp 33.000",
    image: "/images/hero-cup.jpg",
    tags: ["Ceremonial", "Oat Milk"],
    notes: "Umami • Sweet Grass",
  },
  {
    id: "m-chocolate",
    name: "BALI DARK CHOCOLATE 70%",
    category: "NON-COFFEE",
    description: "Artisan single-estate chocolate ganache melted with steamed milk and Madagascar vanilla",
    price: 32000,
    priceFormatted: "Rp 32.000",
    image: "/images/hero-cup.jpg",
    tags: ["Rich", "Decadent"],
    notes: "Fudge • Vanilla Bean",
  },

  // PASTRY
  {
    id: "m-croissant",
    name: "FRENCH BUTTER CROISSANT",
    category: "PASTRY",
    description: "Pure French butter laminate, 36 honeycomb flaky layers, baked fresh every morning",
    price: 24000,
    priceFormatted: "Rp 24.000",
    image: "/images/beans-pile.jpg",
    tags: ["Fresh Baked", "Flaky"],
    notes: "Butter • Golden Crisp",
  },
  {
    id: "m-cinnamon-roll",
    name: "ESPRESSO GLAZED BRIOCHE",
    category: "PASTRY",
    description: "Pillowy brioche dough swirled with Ceylon cinnamon and finished with coffee liqueur glaze",
    price: 28000,
    priceFormatted: "Rp 28.000",
    image: "/images/beans-pile.jpg",
    tags: ["Signature", "Warm"],
    notes: "Cinnamon • Coffee Glaze",
  },
];

export const cafeWalkthroughZones = [
  {
    id: "bar",
    title: "COFFEE BAR",
    subtitle: "Precision Extraction Zone",
    description: "Sleek customized brass Slayer espresso machines, dual Mythos grinders, and our baristas crafting every pour right in front of you.",
    details: ["93.5°C Multi-Boiler Tech", "Bottomless Portafilters", "Custom Ceramic Service"],
    position: { x: "28%", y: "42%" },
  },
  {
    id: "roastery",
    title: "ROASTERY",
    subtitle: "Aroma Master Lab",
    description: "Our in-house 12kg cast iron roaster where fresh green microlots from Brazil and Ethiopia are gently roasted to perfection.",
    details: ["Batch Profiling", "Airflow Modulation", "Daily Cupping Table"],
    position: { x: "64%", y: "30%" },
  },
  {
    id: "lounge",
    title: "LOUNGE",
    subtitle: "Comfort & Contemplation",
    description: "Deep leather armchairs, solid dark walnut tables, soft warm 2700K pendant lamps, and an acoustic soundscape curated for relaxation.",
    details: ["Solid Walnut Finishes", "Diffused Warm Glow", "Ambient Jazz & Lo-Fi"],
    position: { x: "82%", y: "62%" },
  },
  {
    id: "workspace",
    title: "WORKSPACE",
    subtitle: "Creativity & Flow",
    description: "Ergonomic seating, high-speed fiber internet, universal power pods, and natural daylight designed for deep focus.",
    details: ["Fast Fiber Wi-Fi", "Quiet Acoustic Buffer", "Power & USB-C at Every Seat"],
    position: { x: "18%", y: "78%" },
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t-1",
    quote: "Beautiful coffee, incredible atmosphere, and easily one of my favorite places to slow down.",
    author: "RAKA",
    role: "Architect & Specialty Coffee Enthusiast",
    location: "Tuban, Jawa Timur",
    rating: 5,
  },
  {
    id: "t-2",
    quote: "The Caramel Latte is pure art. You taste the true origin characteristics of the bean rather than artificial sweetness. Masterful.",
    author: "MAYA PRATIWI",
    role: "Design Director",
    location: "Surabaya",
    rating: 5,
  },
  {
    id: "t-3",
    quote: "A rare cafe where the interior design, the 3D aesthetic, and the coffee quality all match at the highest international standard.",
    author: "JULIAN ARDIAN",
    role: "Photographer & Roaster",
    location: "Jakarta",
    rating: 5,
  },
];
